-- PostgreSQL dump

-- Create database "taskboard"
CREATE DATABASE taskboard;

-- Table structure for table "task"
DROP TABLE IF EXISTS task;

CREATE TABLE "task" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar(50) DEFAULT null,
  "description" varchar(255) DEFAULT null,
  "icon" varchar(10) DEFAULT null,
  "Status" varchar(15) DEFAULT null
);

